    # Info about you
name: Danh Tran
position: AI Engineer
email: danhtran8mind@gmail.com
#company_name: Company Name
#company_url: https://www.yourcompany.com
place_name: HCMC, VN

# Blog info
title: Danh Tran's Blog (danhtran8mind)
description: This is Danh Tran's Blog (danhtran8mind)
url: https://danhtran8mind.github.io/
main_github_io: false
long_description: >-
    Welcome to Danh Tran's blog! 
    Explore the frontiers of AI, technology, and beyond with insightful articles and exciting projects.

# Social links
github_url: https://github.com/danhtran8mind
linkedin_url: http://www.linkedin.com/in/danhtrancse
social:
  links:
    - http://www.linkedin.com/in/danhtrancse
    - https://github.com/danhtran8mind

# Images + files
logo: https://avatars.githubusercontent.com/u/179741572
cv_url: assets/files/cv.pdf
resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: auto  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: 2b422b
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_background: 232
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38
